### ISSUE TITLE
Implement aligner modifications upstream?

### ISSUE THREAD

**Issue by johanneskoester** [BenLangmead/qtip#1]
Dear Ben,
are there any plans or efforts to push the aligner modifications to upstream? I want to put qtip into [Bioconda](https://bioconda.github.io), but for that, it would be desirable to be able to depend on vanilla aligner packages.

Best,
Johannes

**Comment by johanneskoester** [comment]
Am I right that bowtie2 2.3.0 already works out of the box?

**Comment by johanneskoester** [comment]
@BenLangmead any update on this?

**Comment by BenLangmead** [comment]
Sorry for the delay!  Yes, the Bowtie 2 aligner modifications have been in releases starting with 2.3.1 (I think?  I'll double-check, but I'm confident they're in the latest version.) `qtip` automatically specifies the `--mapq-extra` option when running Bowtie 2, which activates the appropriate feature output.

**Comment by BenLangmead** [comment]
v2.3.2 was the first release that had the exact kind of output used in the paper.  It hasn't changed since then.  (The `--mapq-extra` may also work in prior versions, but it very likely won't give the full set of features used in the paper.)

**Comment by johanneskoester** [comment]
Thanks! What about BWA? Is there a PR already?

**Comment by BenLangmead** [comment]
I just made a BWA MEM PR: https://github.com/lh3/bwa/pull/156

**Comment by johanneskoester** [comment]
Great, thank you!
